version: '2'
services:
  proxy_test:
    container_name: proxy_test
    image: nginx:alpine
    ports:
      - "8082:80/tcp"
    volumes:
    - $PWD/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jenkins
  jenkins_test:
    container_name: jenkins_test
    image: jenkins:2.46.3
    entrypoint: ["/bin/tini", "--", "/usr/local/bin/jenkins.sh"]
    ports:
      - "8080:8080/tcp"
