version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
    - $PWD/docker-compose.yml:/etc/docker-compose.yml:rw
    ports:
    - 9090:9090
