version: '2'
services:
  container1:
    container_name: container1
    build:
      context: .
      dockerfile: Dockerfile1
    entrypoint: ["tail", "-f", "/dev/null"]
  container2:
    container_name: container2
    build:
      context: .
      dockerfile: Dockerfile2
    entrypoint: ["tail", "-f", "/dev/null"]
