# https://github.com/dennyzhang/cheatsheet-kubernetes-A4
apiVersion: v1
kind: Pod
metadata:
  name: dummy
  namespace: default
  labels:
    env: test
spec:
  containers:
  - name: dummy
    image: ubuntu
    # image: busybox
    args: [/bin/sh, -c,
            'echo hello >> /root/test.log; sleep 60']
