version: "3.3"
services:
  fluentd-syslog-li:
    container_name: "fluentd-syslog-li"
    image: fluent/fluentd:v1.2
    volumes:
      - ${PWD}/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "40012:40012"
