version: "3.3"
services:
  fluentd-syslog-li:
    build:
      context: .
    container_name: "fluentd-syslog-li"
    # entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ${PWD}/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "40012:40012"
      # - "40012:40012/udp"
